INSERT INTO USERS (ID, ACTIVE, REAL_NAME, EMAIL, PASSWORD) VALUES (1, true, 'Renata Abreu', 'renata89abreu@gmail.com', '$2a$10$BXrgTIQ.BY9DinOCYQLt9uT4kuNlAu2HXs0G2.Qnf5IeqjzgV0ECG');
INSERT INTO USERS (ID, ACTIVE, REAL_NAME, EMAIL, PASSWORD) VALUES (2, true, 'Ronaldo Junior', 'rondan1991@gmail.com', '$2a$10$BXrgTIQ.BY9DinOCYQLt9uT4kuNlAu2HXs0G2.Qnf5IeqjzgV0ECG');
INSERT INTO USERS (ID, ACTIVE, REAL_NAME, EMAIL, PASSWORD) VALUES (3, true, 'João Victor Fernandes', 'victor.fernandes.07@gmail.com', '$2a$10$BXrgTIQ.BY9DinOCYQLt9uT4kuNlAu2HXs0G2.Qnf5IeqjzgV0ECG');
INSERT INTO USERS (ID, ACTIVE, REAL_NAME, EMAIL, PASSWORD) VALUES (4, true, 'Igor Santos', 'iosorio.santos@gmail.com', '$2a$10$BXrgTIQ.BY9DinOCYQLt9uT4kuNlAu2HXs0G2.Qnf5IeqjzgV0ECG');

INSERT INTO ROLES(ID, ROLE) VALUES (1, 'ADMIN');

INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (3, 1);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (4, 1);